import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const myfont = localFont({
  src: "./fonts/test.ttf",
  display: "swap",
  variable: "--font-myfont",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={myfont.variable}>{children}</body>
    </html>
  );
}
